name: Build

on:
  push:

jobs:
  macOS11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew install tree
          which java
          which ant
          ls -lta /usr/bin/java
          ls -lta /usr/local/bin/ant
          java -version
          ant -version
          tree /usr/local/Cellar
