name: Build

on:
  push:

jobs:
  macOS11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          which java
          which ant
          ls -lta /usr/bin/java
          ls -lta /usr/loca/bin/ant
          java --version
          ant --version

